SELECT EMPLOYEE_ID, DEPARTMENT_ID, MANAGER_ID
FROM HR.EMPLOYEES
WHERE (MANAGER_ID, DEPARTMENT_ID) IN (
    SELECT MANAGER_ID, DEPARTMENT_ID
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID IN (174,141)
)
AND EMPLOYEE_ID NOT IN (174,141);

SELECT A.LAST_NAME, A.SALARY, A.DEPARTMENT_ID, B.SALV
FROM HR.EMPLOYEES A, (
    SELECT DEPARTMENT_ID, AVG(SALARY) as SALV
    FROM HR.EMPLOYEES
    GROUP BY DEPARTMENT_ID) B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND A.SALARY > B.SALV;


SELECT EMPLOYEE_ID, LAST_NAME,DEPARTMENT_ID,
    (CASE
    WHEN DEPARTMENT_ID = (
        SELECT DEPARTMENT_ID
        FROM HR.DEPARTMENTS
        WHERE LOCATION_ID = 1800
        )
    THEN 'Canada' ELSE 'USA' END) AS L
FROM HR.EMPLOYEES
ORDER BY DEPARTMENT_ID;


SELECT EMPLOYEE_ID, LAST_NAME
FROM HR.EMPLOYEES e
ORDER BY (
    SELECT DEPARTMENT_NAME
    FROM HR.DEPARTMENTS d
    WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
);


SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM HR.EMPLOYEES e
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM HR.EMPLOYEES
    WHERE e.DEPARTMENT_ID = DEPARTMENT_ID
);


SELECT e.LAST_NAME, e.EMPLOYEE_ID, e.JOB_ID
FROM HR.EMPLOYEES e
WHERE 2 <= (
    SELECT COUNT(*)
    FROM HR.JOB_HISTORY j
    WHERE j.EMPLOYEE_ID = e.EMPLOYEE_ID
);