-- 1. Command
SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM HR.EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (
    SELECT DEPARTMENT_ID, SALARY
    FROM HR.EMPLOYEES
    WHERE COMMISSION_PCT IS NOT null
);

-- 2. Command
SELECT e1.LAST_NAME, d1.DEPARTMENT_NAME, e1.SALARY
FROM HR.EMPLOYEES e1, HR.DEPARTMENTS d1
WHERE e1.DEPARTMENT_ID = d1.DEPARTMENT_ID 
AND (e1.SALARY, e1.COMMISSION_PCT) IN (
    SELECT e2.SALARY, e2.COMMISSION_PCT
    FROM HR.EMPLOYEES e2, HR.DEPARTMENTS d2
    WHERE e2.DEPARTMENT_ID = d2.DEPARTMENT_ID 
    AND d2.LOCATION_ID = 2400
);

-- 3. Command
SELECT LAST_NAME, HIRE_DATE, SALARY
FROM HR.EMPLOYEES
WHERE (SALARY, COMMISSION_PCT) IN (
    SELECT e.SALARY, e.COMMISSION_PCT
    FROM HR.EMPLOYEES e
    WHERE e.LAST_NAME = 'Kochhar'
)
AND LAST_NAME <> 'Kochhar';

-- 4. Command
SELECT LAST_NAME, JOB_ID, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > (
    SELECT MAX(SALARY)
    FROM HR.EMPLOYEES
    WHERE JOB_ID = 'SA_MAN'
)
ORDER BY SALARY DESC;

-- Alternative
SELECT LAST_NAME, JOB_ID, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > ALL (
    SELECT SALARY
    FROM HR.EMPLOYEES
    WHERE JOB_ID = 'SA_MAN'
)
ORDER BY SALARY DESC;

-- 5. Command
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE LOCATION_ID IN (
        SELECT LOCATION_ID
        FROM LOCATIONS
        WHERE CITY LIKE 'T%'
    )
);


-- 6. Command
WITH dept_averages AS (
    SELECT DEPARTMENT_ID, AVG(SALARY) AS dept_avg
    FROM HR.EMPLOYEES
    WHERE DEPARTMENT_ID IS NOT NULL
    GROUP BY DEPARTMENT_ID
)
SELECT e.LAST_NAME AS ENAME, e.SALARY, e.DEPARTMENT_ID AS DEPTNO, da.dept_avg AS DEPT_AVG
FROM HR.EMPLOYEES e
JOIN dept_averages da ON e.DEPARTMENT_ID = da.DEPARTMENT_ID
WHERE e.SALARY > da.dept_avg
ORDER BY da.dept_avg;

-- 7. Command
-- a.
SELECT LAST_NAME
FROM EMPLOYEES e1
WHERE NOT EXISTS (
    SELECT 1
    FROM EMPLOYEES e2
    WHERE e2.MANAGER_ID = e1.EMPLOYEE_ID
);

-- b.
SELECT LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (
    SELECT MANAGER_ID
    FROM EMPLOYEES
    WHERE MANAGER_ID IS NOT NULL 
);

-- 8. Command
SELECT LAST_NAME
FROM EMPLOYEES e1
WHERE SALARY < (
    SELECT AVG(SALARY)
    FROM EMPLOYEES e2
    WHERE e2.DEPARTMENT_ID = e1.DEPARTMENT_ID
    AND e2.DEPARTMENT_ID IS NOT NULL
);

-- 9. Command
SELECT DISTINCT e1.LAST_NAME
FROM EMPLOYEES e1
WHERE EXISTS (
    SELECT 1
    FROM EMPLOYEES e2
    WHERE e2.DEPARTMENT_ID = e1.DEPARTMENT_ID
    AND e2.HIRE_DATE > e1.HIRE_DATE
    AND e2.SALARY > e1.SALARY
    AND e1.DEPARTMENT_ID IS NOT NULL
);

-- 10. Command
SELECT EMPLOYEE_ID, LAST_NAME,
    (SELECT DEPARTMENT_NAME 
     FROM DEPARTMENTS d 
     WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID) AS DEPARTMENT
FROM EMPLOYEES e
ORDER BY EMPLOYEE_ID;

-- 11.Command
WITH SUMMARY AS (
    SELECT 
        d.DEPARTMENT_NAME,
        SUM(e.SALARY) AS dept_total,
        (SELECT SUM(SALARY) FROM EMPLOYEES) / 8 AS company_threshold
    FROM DEPARTMENTS d
    JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
    GROUP BY d.DEPARTMENT_NAME
)
SELECT DEPARTMENT_NAME, dept_total
FROM SUMMARY
WHERE dept_total > company_threshold;