-- 1. Command
CREATE TABLE DEPT(
    ID NUMBER(7),
    NAME VARCHAR(25)
);

DESCRIBE DEPT;

-- 2. Command
INSERT ALL 
    INTO DEPT VALUES (10, 'Administration')
    INTO DEPT VALUES (20, 'Marketing')
    INTO DEPT VALUES (70, 'Public Relations')
    INTO DEPT VALUES (30, 'Purchasing')
    INTO DEPT VALUES (50, 'Shipping')
    INTO DEPT VALUES (60, 'IT')
    INTO DEPT VALUES (100, 'Finance')
    INTO DEPT VALUES (80, 'Sales')
SELECT * FROM dual;

-- 3. Command
CREATE TABLE EMP(
    ID NUMBER(7),
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    DEPT_ID NUMBER(7)
);

DESCRIBE EMP;

-- 4. Command
ALTER TABLE EMP
MODIFY LAST_NAME VARCHAR2(50);

DESCRIBE EMP;

-- 5. Command
SELECT TABLE_NAME 
FROM USER_TABLES 
WHERE TABLE_NAME IN ('DEPT', 'EMP');

-- 6. Command
CREATE TABLE EMPLOYEES2 (
    ID NUMBER,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(25),
    SALARY NUMBER(8,2),
    DEPT_ID NUMBER(4)
);

-- Altenative
CREATE TABLE EMPLOYEES2 AS
SELECT EMPLOYEE_ID AS ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY,
       DEPARTMENT_ID AS DEPT_ID
FROM EMPLOYEES;

-- 7. Command
DROP TABLE EMP;

-- 8. Command
RENAME EMPLOYEES2 TO EMP;

-- 9. Command
COMMENT ON TABLE DEPT IS 'Contains Id, Name';
COMMENT ON TABLE EMP IS 'Contains Id, Names, Salary';



SELECT TABLE_NAME, COMMENTS 
FROM USER_TAB_COMMENTS 
WHERE TABLE_NAME IN ('DEPT', 'EMP');

-- 10. Command
ALTER TABLE EMP
DROP COLUMN FIRST_NAME;

DESCRIBE EMP;

-- 11. Command
ALTER TABLE EMP
SET UNUSED COLUMN DEPT_ID;

DESCRIBE EMP;

-- 12. Command
ALTER TABLE EMP
DROP UNUSED COLUMNS;

DESCRIBE EMP;