-- 1. Command
SELECT LAST_NAME, HIRE_DATE
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM HR.EMPLOYEES
    WHERE LAST_NAME = '&user_prompt'
)
AND LAST_NAME <> '&user_prompt';

-- 2. Command
SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM HR.EMPLOYEES
)
ORDER BY SALARY;

-- 3. Command
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM HR.EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT E2.DEPARTMENT_ID
    FROM HR.EMPLOYEES E2
    WHERE UPPER(E2.LAST_NAME) LIKE '%U%'
);

-- 4. Command
SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID
FROM HR.EMPLOYEES JOIN HR.DEPARTMENTS
USING (DEPARTMENT_ID)
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM HR.DEPARTMENTS 
    WHERE LOCATION_ID = 1700
);

-- Extended:
SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID
FROM HR.EMPLOYEES JOIN HR.DEPARTMENTS
USING (DEPARTMENT_ID)
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM HR.DEPARTMENTS 
    WHERE LOCATION_ID = '&user_prompt'
);

-- 5. Command
SELECT LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE MANAGER_ID IN (
    SELECT EMPLOYEE_ID
    FROM HR.EMPLOYEES
    WHERE LAST_NAME = 'King'
);

-- 6. Command
SELECT DEPARTMENT_ID, LAST_NAME, JOB_ID
FROM HR.DEPARTMENTS JOIN HR.EMPLOYEES 
USING (DEPARTMENT_ID)
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM HR.DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'Executive'
);

-- 7. Command
SELECT E.EMPLOYEE_ID, E.LAST_NAME, SALARY
FROM HR.EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT E2.DEPARTMENT_ID
    FROM HR.EMPLOYEES E2
    WHERE UPPER(E2.LAST_NAME) LIKE '%U%'
) AND SALARY > (
    SELECT AVG(SALARY)
    FROM HR.EMPLOYEES
);