-- DROP TABLE INTERACTIONS CASCADE CONSTRAINTS;

CREATE TABLE Companies (
    company_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(255) NOT NULL UNIQUE
);

CREATE TABLE Drugs (
    drug_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_name     VARCHAR2(255) NOT NULL,
    product_name  VARCHAR2(255),
    drug_category VARCHAR2(255),
    company_id    NUMBER,
    CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES Companies(company_id)
);

CREATE TABLE Side_Effects (
    side_effect_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id          NUMBER,
    side_effect_name VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_drug_side_effect FOREIGN KEY (drug_id) REFERENCES Drugs(drug_id)
);

CREATE TABLE Interactions (
    interaction_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id         NUMBER,
    interacts_with  VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_drug_interaction FOREIGN KEY (drug_id) REFERENCES Drugs(drug_id)
);

CREATE TABLE Diseases (
    disease_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_name     VARCHAR2(255) NOT NULL UNIQUE,
    disease_category VARCHAR2(255)
);

CREATE TABLE Drug_Diseases (
    drug_id    NUMBER,
    disease_id NUMBER,
    PRIMARY KEY (drug_id, disease_id),
    CONSTRAINT fk_drug_dd FOREIGN KEY (drug_id) REFERENCES Drugs(drug_id),
    CONSTRAINT fk_disease_dd FOREIGN KEY (disease_id) REFERENCES Diseases(disease_id)
);

CREATE TABLE Clinical_Trials (
    trial_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_title       VARCHAR2(512) NOT NULL,
    start_date        DATE,
    completion_date   DATE,
    participants      NUMBER,
    status            VARCHAR2(100),
    institution       VARCHAR2(255),
    address           VARCHAR2(255),
    main_researcher   VARCHAR2(255)
);

CREATE TABLE Trial_Conditions (
    condition_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id       NUMBER,
    condition_name VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_trial_condition FOREIGN KEY (trial_id) REFERENCES Clinical_Trials(trial_id)
);

CREATE TABLE Drug_Trials (
    drug_id  NUMBER,
    trial_id NUMBER,
    PRIMARY KEY (drug_id, trial_id),
    CONSTRAINT fk_drug_dt FOREIGN KEY (drug_id) REFERENCES Drugs(drug_id),
    CONSTRAINT fk_trial_dt FOREIGN KEY (trial_id) REFERENCES Clinical_Trials(trial_id)
);

INSERT INTO Companies (company_name) VALUES ('ImClone LLC');
INSERT INTO Companies (company_name) VALUES ('Eisai Inc.');
INSERT INTO Companies (company_name) VALUES ('Immunex Corporation');
INSERT INTO Companies (company_name) VALUES ('ImaRx Therapeutics, Inc.');
INSERT INTO Companies (company_name) VALUES ('Eli Lilly and Company');
INSERT INTO Companies (company_name) VALUES ('GM Pharamceuticals, Inc');
INSERT INTO Companies (company_name) VALUES ('Vertical Pharmaceuticals, Inc');
INSERT INTO Companies (company_name) VALUES ('Physicians Total Care, Inc.');
INSERT INTO Companies (company_name) VALUES ('Alcon Laboratories, Inc.');
INSERT INTO Companies (company_name) VALUES ('Stat Rx USA');
INSERT INTO Companies (company_name) VALUES ('CutisPharma, Inc.');
INSERT INTO Companies (company_name) VALUES ('A-S Medication Solutions LLC');
INSERT INTO Companies (company_name) VALUES ('Chain Drug Consortium');
INSERT INTO Companies (company_name) VALUES ('Chattem, Inc.');
INSERT INTO Companies (company_name) VALUES ('Family Dollar Services Inc');
INSERT INTO Companies (company_name) VALUES ('Ferndale Laboratories, Inc.');

INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('cetuximab', 'ERBITUX', 'Antineoplastic agents', (SELECT company_id FROM Companies WHERE company_name = 'ImClone LLC'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('denileukin diftitox', 'Ontak', 'Antineoplastic agents', (SELECT company_id FROM Companies WHERE company_name = 'Eisai Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('etanercept', 'ENBREL', 'Antirheumatic agents', (SELECT company_id FROM Companies WHERE company_name = 'Immunex Corporation'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('etanercept', 'ENBREL', 'Immunomodulatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Immunex Corporation'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('urokinase', 'Kinlytic', 'Thrombolytic agents', (SELECT company_id FROM Companies WHERE company_name = 'ImaRx Therapeutics, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('abciximab', 'REOPRO', 'Anticoagulants', (SELECT company_id FROM Companies WHERE company_name = 'Eli Lilly and Company'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('abciximab', 'REOPRO', 'Antiplatelet agents', (SELECT company_id FROM Companies WHERE company_name = 'Eli Lilly and Company'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'MyOxin', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'GM Pharamceuticals, Inc'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Trioxin', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Vertical Pharmaceuticals, Inc'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Cipro', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Physicians Total Care, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'CIPRO', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Alcon Laboratories, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Cipro HC', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Stat Rx USA'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'FIRST Dukes Mouthwash Compounding', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'CutisPharma, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'FIRST Marys Mouthwash Compounding', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'CutisPharma, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Hydrocortisone', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'A-S Medication Solutions LLC'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Premier Value ', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Chain Drug Consortium'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Cortizone 10 Poison Ivy Relief Pads', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Chattem, Inc.'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Family Wellness Hydrocortisone', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Family Dollar Services Inc'));
INSERT INTO Drugs (drug_name, product_name, drug_category, company_id) VALUES ('hydrocortisone', 'Pramosone E', 'Anti-inflammatory agents', (SELECT company_id FROM Companies WHERE company_name = 'Ferndale Laboratories, Inc.'));


INSERT INTO Diseases (disease_name, disease_category) VALUES ('Adenocarcinoma', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Complementary component deficiency', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('IgG receptor I, phagocytic, familial deficiency of', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Lupus erythematosus', 'Connective tissue disorder');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Lymphoma', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Neutropenia', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Nonsmall cell lung cancer', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Viral infection', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Adenocarcinoma of lung, response to tyrosine kinase inhibitor in, 211980', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('C1q deficiency, type A', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('C1q deficiency, type B', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('C1s deficiency, isolated', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Lupus nephritis, susceptibility to', 'Connective tissue disorder');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Lymphoma, progression of', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Neutropenia, alloimmune neonatal', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Nonsmall cell lung cancer, response to tyrosine kinase inhibitor in, 211980', 'Cancer');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Viral infections, recurrent', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Interleukin-2 receptor, alpha chain, deficiency of', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Severe combined immunodeficiency', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Combined immunodeficiency', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Combined immunodeficiency, X-linked, moderate, 312863', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Severe combined immunodeficiency, X-linked, 300400', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Asthma', 'Respiratory');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Dementia', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Malaria', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Migraine', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Myocardial infarction', 'Cardiovascular');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Sepsis', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Asthma, susceptibility to, 600807', 'Respiratory');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Dementia, vascular, susceptibility to', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Malaria, cerebral, susceptibility to', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Migraine without aura, susceptibility to, 157300', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Myocardial infarction, susceptibility to', 'Cardiovascular');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Septic shock, susceptibility to', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Alzheimer disease', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Conjunctivitis, ligneous', 'Ophthamological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Plasminogen deficiency', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Alzheimer disease, late-onset, susceptibility to, 104300', 'Neurological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Conjunctivitis, ligneous, 217090', 'Ophthamological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Plasminogen Tochigi disease', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Glanzmann thrombasthenia', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Glanzmann thrombasthenia, type B', 'Hematological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Atherosclerosis', 'Cardiovascular');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Cortisol resistance', 'Endocrine');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Obesity', 'Nutritional');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Asthma, dimished response to antileukotriene treatment in, 600807', 'Respiratory');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Atherosclerosis, susceptibility to', 'Cardiovascular');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Malaria, resistance to, 248310', 'Immunological');
INSERT INTO Diseases (disease_name, disease_category) VALUES ('Obesity, adrenal insufficiency, and red hair', 'Nutritional');


INSERT INTO Clinical_Trials (trial_title, start_date, completion_date, participants, status, institution, address, main_researcher) VALUES ('Immune Response on Neoadjuvant Therapy in Non-small-cell Lung Cancer (NSCLC)', TO_DATE('2007-01-01', 'YYYY-MM-DD'), TO_DATE('2011-06-01', 'YYYY-MM-DD'), NULL, 'Completed', 'Medical University of Vienna', 'Austria', 'Wolfgang Hilbe');
INSERT INTO Clinical_Trials (trial_title, start_date, completion_date, participants, status, institution, address, main_researcher) VALUES ('Can We Miss Pigmented Lesions in Psoriasis Patients?', TO_DATE('2007-09-01', 'YYYY-MM-DD'), TO_DATE('2012-04-01', 'YYYY-MM-DD'), NULL, 'Completed', 'University of Alabama at Birmingham', 'United States', 'Boni Elewski, MD');
INSERT INTO Clinical_Trials (trial_title, start_date, completion_date, participants, status, institution, address, main_researcher) VALUES ('Addition of Etanercept and Extracorporeal Photopheresis (ECP) to Standard Graft-Versus-Host Disease (GVHD) Prophylaxis in Stem Cell Transplant', TO_DATE('2009-03-01', 'YYYY-MM-DD'), TO_DATE('2015-09-01', 'YYYY-MM-DD'), NULL, 'Active, not recruiting', 'University of Michigan Cancer Center', 'United States', 'John Levine, MD');
INSERT INTO Clinical_Trials (trial_title, start_date, completion_date, participants, status, institution, address, main_researcher) VALUES ('Efficacy Study on Early Versus Late Abciximab Administration During Primary Coronary Angioplasty', TO_DATE('2006-04-01', 'YYYY-MM-DD'), TO_DATE('2008-12-01', 'YYYY-MM-DD'), NULL, 'Completed', 'University of Pisa', 'Italy', 'Prof. Anna Sonia Petronio');
INSERT INTO Clinical_Trials (trial_title, start_date, completion_date, participants, status, institution, address, main_researcher) VALUES ('Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu', TO_DATE('2010-03-01', 'YYYY-MM-DD'), TO_DATE('2011-12-01', 'YYYY-MM-DD'), NULL, 'Terminated', 'University of Versailles', 'France', 'Djillali Annane');


INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), 'somnolence');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), 'headache');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), 'cough');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), 'renal failure');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), 'carcinoma');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Adenocarcinoma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Immune Response on Neoadjuvant Therapy in Non-small-cell Lung Cancer (NSCLC)'));
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Immune Response on Neoadjuvant Therapy in Non-small-cell Lung Cancer (NSCLC)'), 'Carcinoma, Non-small-cell Lung');
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Immune Response on Neoadjuvant Therapy in Non-small-cell Lung Cancer (NSCLC)'), 'Laryngeal Neoplasms');
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Immune Response on Neoadjuvant Therapy in Non-small-cell Lung Cancer (NSCLC)'), 'Mouth Neoplasms');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Complementary component deficiency'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'IgG receptor I, phagocytic, familial deficiency of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lupus erythematosus'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lymphoma'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Neutropenia'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Nonsmall cell lung cancer'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Viral infection'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Adenocarcinoma of lung, response to tyrosine kinase inhibitor in, 211980'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type A'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type B'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1s deficiency, isolated'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lupus nephritis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lymphoma, progression of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Neutropenia, alloimmune neonatal'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Nonsmall cell lung cancer, response to tyrosine kinase inhibitor in, 211980'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'cetuximab' AND product_name = 'ERBITUX'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Viral infections, recurrent'));
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), 'dizziness');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), 'headache');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), 'pain');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), 'dehydration');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), 'vasodilatation');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Interleukin-2 receptor, alpha chain, deficiency of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Severe combined immunodeficiency'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Combined immunodeficiency'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Combined immunodeficiency, X-linked, moderate, 312863'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'denileukin diftitox' AND product_name = 'Ontak'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Severe combined immunodeficiency, X-linked, 300400'));
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), 'dizziness');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), 'abdominal pain');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), 'nausea');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), 'melanoma');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Can We Miss Pigmented Lesions in Psoriasis Patients?'));
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Can We Miss Pigmented Lesions in Psoriasis Patients?'), 'Non-melanoma Skin Cancer');
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Can We Miss Pigmented Lesions in Psoriasis Patients?'), 'Psoriasis');
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Can We Miss Pigmented Lesions in Psoriasis Patients?'), 'Melanoma');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Complementary component deficiency'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Dementia'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'IgG receptor I, phagocytic, familial deficiency of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lupus erythematosus'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lymphoma'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Migraine'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Myocardial infarction'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Neutropenia'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Sepsis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Viral infection'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, susceptibility to, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type A'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type B'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1s deficiency, isolated'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Dementia, vascular, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lupus nephritis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lymphoma, progression of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, cerebral, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Migraine without aura, susceptibility to, 157300'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Myocardial infarction, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Neutropenia, alloimmune neonatal'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Septic shock, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'etanercept' AND product_name = 'ENBREL'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Viral infections, recurrent'));
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), 'back pain');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), 'fever');
INSERT INTO Side_Effects (drug_id, side_effect_name) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), 'nausea');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Alzheimer disease'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Conjunctivitis, ligneous'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Plasminogen deficiency'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Alzheimer disease, late-onset, susceptibility to, 104300'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Conjunctivitis, ligneous, 217090'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'urokinase' AND product_name = 'Kinlytic'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Plasminogen Tochigi disease'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Complementary component deficiency'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Efficacy Study on Early Versus Late Abciximab Administration During Primary Coronary Angioplasty'));
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Efficacy Study on Early Versus Late Abciximab Administration During Primary Coronary Angioplasty'), 'Myocardial Infarction');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Glanzmann thrombasthenia'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'IgG receptor I, phagocytic, familial deficiency of'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lupus erythematosus'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Lymphoma'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Neutropenia'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Viral infection'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type A'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1q deficiency, type B'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'C1s deficiency, isolated'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'abciximab' AND product_name = 'REOPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Glanzmann thrombasthenia, type B'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'), 'Pneumonia, Viral');
INSERT INTO Trial_Conditions (trial_id, condition_name) VALUES ((SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'), 'Influenza in Humans');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'MyOxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Trioxin'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'CIPRO'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cipro HC'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Dukes Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'FIRST Marys Mouthwash Compounding'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Premier Value '), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Cortizone 10 Poison Ivy Relief Pads'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Cortisol resistance'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma, dimished response to antileukotriene treatment in, 600807'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Atherosclerosis, susceptibility to'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Malaria, resistance to, 248310'));
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Family Wellness Hydrocortisone'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Obesity, adrenal insufficiency, and red hair'));
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Pramosone E'), 'butabarbital');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Pramosone E'), 'salsalate');
INSERT INTO Interactions (drug_id, interacts_with) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Pramosone E'), 'midodrine');
INSERT INTO Drug_Diseases (drug_id, disease_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Pramosone E'), (SELECT disease_id FROM Diseases WHERE disease_name = 'Asthma'));
INSERT INTO Drug_Trials (drug_id, trial_id) VALUES ((SELECT drug_id FROM Drugs WHERE drug_name = 'hydrocortisone' AND product_name = 'Pramosone E'), (SELECT trial_id FROM Clinical_Trials WHERE trial_title = 'Low Doses Corticosteroids as Adjuvant Therapy for the Treatment of Severe H1N1 Flu'));

-- Optional: Query to verify data insertion
SELECT COUNT(*) FROM Drugs
NATURAL JOIN SIDE_EFFECTS
WHERE SIDE_EFFECT_NAME = 'nausea';

SELECT COUNT(*) FROM DRUGS
NATURAL JOIN INTERACTIONS
WHERE INTERACTS_WITH = 'butabarbital';

SELECT * FROM Drugs
NATURAL JOIN SIDE_EFFECTS
WHERE SIDE_EFFECT_NAME = 'cough';
