-- 1. True

-- 2. False

-- 3. True

-- 4. Command:
SELECT MAX(SALARY) AS "Maximum", MIN(SALARY) AS "Minimum", ROUND(SUM(SALARY)) AS "Sum", ROUND(AVG(SALARY)) AS "Average" 
FROM HR.EMPLOYEES;

-- 5. Command:
SELECT JOB_ID, MAX(SALARY) AS "Maximum", MIN(SALARY) AS "Minimum", ROUND(SUM(SALARY)) AS "Sum", ROUND(AVG(SALARY)) AS "Average" 
FROM HR.EMPLOYEES
GROUP BY JOB_ID;

-- 6. Command: 
SELECT JOB_ID, COUNT(*)
FROM HR.EMPLOYEES
GROUP BY JOB_ID;
 
SELECT JOB_ID, COUNT(*)
FROM HR.EMPLOYEES
WHERE JOB_ID = '&USER_PROMPT'
GROUP BY JOB_ID;

-- 7. Command:
SELECT COUNT(DISTINCT MANAGER_ID) AS "Number of Managers"
FROM HR.EMPLOYEES;

-- 8. Command:
SELECT MAX(SALARY)-MIN(SALARY) AS "DIFFERENCE"
FROM HR.EMPLOYEES;

-- 9. Command:
SELECT MANAGER_ID, MIN(SALARY)
FROM HR.EMPLOYEES
WHERE MANAGER_ID IS NOT null
GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000 
ORDER BY MIN(SALARY) DESC;

-- 10. Command: 
SELECT COUNT(*) AS "TOTAL",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY') = '1995' THEN 1 ELSE 0 END) AS "1995",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY') = '1996' THEN 1 ELSE 0 END) AS "1996",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY') = '1997' THEN 1 ELSE 0 END) AS "1997",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY') = '1998' THEN 1 ELSE 0 END) AS "1998"
FROM HR.EMPLOYEES;

-- 11. Command:
SELECT 
JOB_ID AS "Job",
    SUM(CASE WHEN department_id = 20 THEN salary END) AS "Dept 20",
    SUM(CASE WHEN department_id = 50 THEN salary END) AS "Dept 50",
    SUM(CASE WHEN department_id = 80 THEN salary END) AS "Dept 80",
    SUM(CASE WHEN department_id = 90 THEN salary END) AS "Dept 90",
    SUM(salary) AS "Total"
FROM HR.EMPLOYEES
GROUP BY JOB_ID
ORDER BY JOB_ID;