-- 1. Command:
SELECT LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > 12000;

-- 2. Command:
SELECT LAST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 176;

-- 3. Command:
SELECT LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;

-- 4. Command:
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM HR.EMPLOYEES
WHERE LAST_NAME IN ('Matos', 'Taylor')
ORDER BY HIRE_DATE;

-- Alternative Command:
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM HR.EMPLOYEES
WHERE LAST_NAME = 'Matos' OR LAST_NAME = 'Taylor'
ORDER BY HIRE_DATE;

-- 5. Command:
SELECT LAST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (20,50)
ORDER BY LAST_NAME;

-- 6. Command:

SELECT LAST_NAME AS "Employee" , SALARY AS "Monthly Salary"
FROM HR.EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000
AND DEPARTMENT_ID IN (20, 50);

-- 7. Command: 

SELECT LAST_NAME, HIRE_DATE
FROM HR.EMPLOYEES
WHERE HIRE_DATE LIKE '%94%';

-- 8. Command:

SELECT LAST_NAME, JOB_ID
FROM HR.EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- 9. Command: 

SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY 2 DESC, 3 DESC;

-- 10. Command:

SELECT LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > &User_Prompt;

-- 11. Command:

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE MANAGER_ID = &manager_ID
ORDER BY &User_Choice;

-- 12. Command:

SELECT LAST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '__a%';

-- 13. Command:

SELECT LAST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%';

-- 14. Command: 

SELECT LAST_NAME, JOB_ID, SALARY
FROM HR.EMPLOYEES
WHERE (JOB_ID LIKE 'S%REP' OR JOB_ID LIKE 'ST%CLERK') AND SALARY NOT IN (2500, 3500, 7000);

-- 15. Command:  


SELECT LAST_NAME AS "Employee" , SALARY AS "Monthly Salary", COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) AND (COMMISSION_PCT = 0.2);