-- 1. Command
ALTER TABLE EMP 
ADD CONSTRAINT my_emp_id_pk PRIMARY KEY (ID);

-- 2. Command
ALTER TABLE DEPT
ADD CONSTRAINT my_deptid_pk PRIMARY KEY (ID);

-- 3. Command
ALTER TABLE EMP
ADD DEPT_ID NUMBER(4);

ALTER TABLE EMP 
ADD CONSTRAINT my_emp_dept_id_fk 
FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID);

-- 4. Command
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE C
FROM USER_CONSTRAINTS;

-- 5. Command
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_NAME NOT IN ('MY_EMPLOYEE');

-- 6. Command
ALTER TABLE EMP
ADD COMMISSION NUMBER(2,2) CHECK (COMMISSION > 0);

-- Alternative
ALTER TABLE EMP
ADD COMMISSION NUMBER(2,2) CONSTRAINT emp_commission_ck CHECK (COMMISSION > 0);