-- 1. Command: 
SELECT sysdate AS "Date";

-- 2. Command:
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY + (SALARY * 0.155)) AS "New Salary"
FROM  HR.EMPLOYEES;

-- 3. CSV Inclusion

-- 4. Command: 
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY + (SALARY * 0.155)) AS "New Salary", (SALARY * 0.155) AS "Increase"
FROM  HR.EMPLOYEES;

-- 5. Command:
SELECT INITCAP(LAST_NAME) AS "Name", LENGTH(LAST_NAME) AS "Length"
FROM HR.EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE 'J%' OR UPPER(LAST_NAME) LIKE 'A%' OR UPPER(LAST_NAME) LIKE 'M%'
ORDER BY LAST_NAME;


SELECT INITCAP(LAST_NAME) AS "Name", LENGTH(LAST_NAME) AS "Length"
FROM HR.EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE '&user_prompt%'
ORDER BY LAST_NAME;


SELECT INITCAP(LAST_NAME) AS "Name", LENGTH(LAST_NAME) AS "Length"
FROM HR.EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE UPPER('&user_prompt') || '%'
ORDER BY LAST_NAME;

-- 6. Command: 
SELECT LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "MONTHS_WORKED"
FROM HR.EMPLOYEES
ORDER BY MONTHS_WORKED;


-- 7. Command: 
SELECT LAST_NAME, LPAD(SALARY, 15, '$') AS "SALARY"
FROM HR.EMPLOYEES;


-- 8. Command: 
SELECT SUBSTR(LAST_NAME,1,8) || ' ' || LPAD('*', FLOOR(SALARY / 1000), '*') AS "EMPLOYEES_AND_THEIR_SALARIES"
FROM HR.EMPLOYEES
ORDER BY SALARY DESC;

-- 9. Command:
SELECT LAST_NAME,  TRUNC((sysdate-HIRE_DATE)/7, 0) AS "TENURE"
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER BY TENURE DESC;